platform: x64

environment:
  matrix:
    - compiler: msvc
      ARCH: amd64
      CFG: release
    - compiler: msvc
      ARCH: x86
      CFG: release
    - compiler: msvc
      ARCH: amd64
      CFG: debug
    - compiler: msvc
      ARCH: x86
      CFG: debug

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-ragel"

build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%'
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; PATH=$PATH:/mingw64/bin:/mingw32/bin; ./autogen.sh; make distdir"
  - cd harfbuzz-*\win32
  - nmake /f Makefile.vc CFG=%CFG% DIRECTWRITE=1

# disable automatic tests
test: off
