platform: x64

environment:
  matrix:
    - compiler: msvc
      generator: Visual Studio 14
      vcvarsallpath: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      arch: amd64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: msvc
      generator: Visual Studio 15
      vcvarsallpath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      arch: x86

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      compiler: msvc
      generator: Visual Studio 16
      vcvarsallpath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
      arch: amd64

build_script:
  - set "PYTHON_ROOT=C:\python37-x64"
  - set "PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%"
  - 'if "%compiler%"=="msvc" pip install --upgrade meson'
  - 'if "%compiler%"=="msvc" pip install fonttools'
  - 'if "%compiler%"=="msvc" "%vcvarsallpath%" %arch% && meson setup build --wrap-mode=default --buildtype=release -Dglib=enabled -Dfreetype=enabled -Dgdi=enabled -Ddirectwrite=enabled && meson test --print-errorlogs --suite=harfbuzz -Cbuild'

cache:
  - c:\tools\vcpkg\installed\

notifications:
  - provider: Email
    to:
      - harfbuzz-bots-chatter@googlegroups.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# disable automatic tests
test: off
