name: msvc

on:
  push:
  pull_request:

jobs:
  msvc:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2016, windows-latest]
        include:
          - name: msvc-2017-x86
            os: windows-2016
            VCVARSALLPATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
            ARCH: x86
          - name: msvc-2019-amd64
            os: windows-latest
            VCVARSALLPATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
            ARCH: amd64
    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build
        shell: cmd
        run: |
          pip install --upgrade meson ninja fonttools
          "${{ matrix.VCVARSALLPATH }}" ${{ matrix.ARCH }} && meson setup build --wrap-mode=default --buildtype=release -Dglib=enabled -Dfreetype=enabled -Dgdi=enabled -Ddirectwrite=enabled && meson test --print-errorlogs --suite=harfbuzz -Cbuild
      - name: Test
        shell: cmd
        run: |
          meson test --print-errorlogs --suite=harfbuzz -Cbuild
