name: sanitizers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install pkg-config clang ragel gcovr gtk-doc-tools libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev python3 python3-setuptools ninja-build # libgirepository1.0-dev
    - name: install meson
      run: sudo pip3 install meson

    - name: address+undefined sanitizer
      run: |
      meson build -Db_sanitize=address,undefined -Dglib=enabled -Dcairo=enabled -Dicu=enabled -Dgraphite=enabled -Dfreetype=enabled
      meson test --print-errorlogs -Cbuild && rm -rf build
    - name: thread sanitizer
      run: |
      meson build -Db_sanitize=thread -Dglib=enabled -Dcairo=enabled -Dicu=enabled -Dgraphite=enabled -Dfreetype=enabled
      meson test --print-errorlogs -Cbuild && rm -rf build

    # - name: configure memory sanitizer
    #   run: meson build -Db_sanitize=memory -Dglib=enabled -Dcairo=enabled -Dicu=enabled -Dgraphite=enabled -Dfreetype=enabled
    # - name: run memory sanitizer
    #   run: meson test --print-errorlogs -Cbuild && rm -rf build
